FROM ubuntu:20.04
ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_FRONTEND noninteractive
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE DontWarn
RUN apt-get -y update \
    && apt-get -y upgrade
RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y python3.9 python3-distutils python3-pip python3-apt
# Install libzip5
# https://askubuntu.com/questions/1071789/how-to-update-libzip-to-1-2-on-ubuntu-18-04-and-php-7-2
RUN apt-get install -y unzip zip zlib1g-dev libzip-dev libzip5 wget libeigen3-dev git
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null |  apt-key add -
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
RUN apt-get -y update \
    && apt-get -y upgrade
RUN apt-get install -y  cmake
WORKDIR /workspace
RUN mkdir /workspace/katago
RUN cd /workspace/katago \
    && wget https://media.katagotraining.org/uploaded/networks/models/kata1/kata1-b18c384nbt-s6582191360-d3422816034.bin.gz
RUN cd /workspace/katago \
    && git clone https://github.com/lightvector/KataGo.git \
    && cd KataGo/cpp \
    && cmake . -DUSE_BACKEND=EIGEN \
    && make -j 4
RUN rm -rf /var/cache/*
RUN mv /workspace/katago/KataGo/cpp/katago /workspace/katago/katago
WORKDIR /app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY katago.py .
COPY main.py .
COPY analysis.cfg .
CMD ["python3", "main.py"]
