M48
; DRILL file {KiCad (6.0.7-1)-1} date 2022 December 02, Friday 15:50:48
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-02T15:50:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X39.54Y-54.16
X105.98Y-53.92
X170.85Y-54.72
T0
M30
